// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXmZuwqOWWNYdYFC_vbuElyJcWtJL7Uhs',
    appId: '1:739191775662:web:c12038256ce4cb7eff283f',
    messagingSenderId: '739191775662',
    projectId: 'squashapp-886b5',
    authDomain: 'squashapp-886b5.firebaseapp.com',
    storageBucket: 'squashapp-886b5.appspot.com',
    measurementId: 'G-SLWZTWVHDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6sTRjP3gO1pzh9hWlGdxFkjC5VH0kfig',
    appId: '1:739191775662:android:645b7575f1f21f30ff283f',
    messagingSenderId: '739191775662',
    projectId: 'squashapp-886b5',
    storageBucket: 'squashapp-886b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaHhA8OYJfvgy7Hf239zJYovDoz2P9Qc8',
    appId: '1:739191775662:ios:0135c25a3140b892ff283f',
    messagingSenderId: '739191775662',
    projectId: 'squashapp-886b5',
    storageBucket: 'squashapp-886b5.appspot.com',
    iosBundleId: 'no.chrisscorp.squashmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaHhA8OYJfvgy7Hf239zJYovDoz2P9Qc8',
    appId: '1:739191775662:ios:c07117a7bf7f92e5ff283f',
    messagingSenderId: '739191775662',
    projectId: 'squashapp-886b5',
    storageBucket: 'squashapp-886b5.appspot.com',
    iosBundleId: 'no.chrisscorp.squashmate.RunnerTests',
  );
}
